### PR TITLE
Update CatMaker.java with some new code

### PR DESCRIPTION
**Pull request by BruceGiese**
Here's some more stuff to learn about Java.

### CODE REVIEW

**Comment by BruceGiese** [comment]
Hey Art,
This is a request for changes to your project.  You can merge this into your code (somehow, I'm not sure how) to see some more interesting things you can do in Java.

**Comment by Gryphonlover** [comment]
Done

**Comment by Gryphonlover** [comment]
How do I update the code on my computer again?

**Comment by Gryphonlover** [comment]
There is a bug in the code!

**Pull request merged**
